version: "3"

networks:
  mongodb-network:
    driver: bridge

services:
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    networks:
      - mongodb-network
  mongoexpress:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - mongodb-network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
